export const ProductErrors = {
  PRODUCT_NOT_FOUND: 'Product not found',
  PRODUCT_ALREADY_EXISTS: 'Product already exists',
  PRODUCT_NOT_FOUND_OR_DELETED: 'Product not found or deleted',
  PRODUCT_STOCK_NOT_ENOUGH: 'Product stock not enough',
  PRODUCT_NOT_ACTIVE: 'Product not active',
  PRODUCT_NOT_FOUND_IN_CART: 'Product not found in cart',
  PRODUCT_NOT_FOUND_IN_WISHLIST: 'Product not found in wishlist',
  PRODUCT_NOT_FOUND_IN_ORDER: 'Product not found in order',
  PRODUCT_NOT_FOUND_IN_FAVORITE: 'Product not found in favorite',
  PRODUCT_NOT_FOUND_IN_RECENTLY_VIEWED: 'Product not found in recently viewed',
  PRODUCT_NOT_FOUND_IN_RECOMMENDED: 'Product not found in recommended',
  PRODUCT_NOT_FOUND_IN_POPULAR: 'Product not found in popular',
  PRODUCT_NOT_FOUND_IN_BEST_SELLER: 'Product not found in best seller',
  PRODUCT_NOT_FOUND_IN_NEW_ARRIVAL: 'Product not found in new arrival',
  PRODUCT_NOT_FOUND_IN_CATEGORY: 'Product not found in category',
  PRODUCT_NOT_FOUND_IN_SUB_CATEGORY: 'Product not found in sub category',
  PRODUCT_NOT_FOUND_IN_BRAND: 'Product not found in brand',
  PRODUCT_NOT_FOUND_IN_SEARCH: 'Product not found in search',
  PRODUCT_NOT_FOUND_IN_FILTER: 'Product not found in filter',
  PRODUCT_NOT_FOUND_IN_RELATED: 'Product not found in related',
  PRODUCT_NOT_FOUND_IN_SIMILAR: 'Product not found in similar',
  PRODUCT_NOT_FOUND_IN_SAME_BRAND: 'Product not found in same brand',
  PRODUCT_NOT_FOUND_IN_SAME_CATEGORY: 'Product not found in same category',
  PRODUCT_NOT_FOUND_IN_SAME_SUB_CATEGORY:
    'Product not found in same sub category',
  PRODUCT_NOT_FOUND_IN_SAME_COLLECTION: 'Product not found in same collection',
  PRODUCT_NOT_FOUND_IN_SAME_DESIGNER: 'Product not found in same designer',
  PRODUCT_NOT_FOUND_IN_SAME_MAKER: 'Product not found in same maker',
  PRODUCT_NOT_FOUND_IN_SAME_ARTIST: 'Product not found in same artist',
  PRODUCT_NOT_FOUND_IN_SAME_ARTISAN: 'Product not found in same artisan',
  PRODUCT_NOT_FOUND_IN_SAME_CRAFTSMAN: 'Product not found in same craftsman',
  PRODUCT_NOT_FOUND_IN_SAME_MANUFACTURER:
    'Product not found in same manufacturer',

  CATEGORY_NOT_FOUND: 'Category not found',
};
