// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty.pb";

export const protobufPackage = "order";

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0,
  CREATED = 1,
  COMPLETED = 2,
  CANCELLED = 3,
  INVENTORY_RESERVED = 4,
  PAYMENT_PENDING = 5,
  PAYMENT_FAILED = 6,
  PAYMENT_SUCCESS = 7,
  UNRECOGNIZED = -1,
}

export enum OrderWorkflowStatus {
  ORDER_WORKFLOW_STATUS_UNSPECIFIED = 0,
  ORDER_WORKFLOW_STATUS_PROCESSING = 1,
  ORDER_WORKFLOW_STATUS_COMPLETED = 2,
  ORDER_WORKFLOW_STATUS_CANCELLED = 3,
  UNRECOGNIZED = -1,
}

export interface OrderData {
  id: string;
  code: string;
  items: OrderItem[];
  userId: string;
  status: OrderStatus;
  totalAmount: number;
}

export interface OrderItemRequest {
  productId: string;
  quantity: number;
}

export interface OrderItem {
  productId: string;
  productName: string;
  productPrice: number;
  quantity: number;
  totalAmount: number;
}

/** Create */
export interface CreateRequest {
  items: OrderItemRequest[];
  userId: string;
}

export interface CreateResponse {
  orderCode: string;
  workflowId: string;
  paymentUrl: string;
}

/** FindOne */
export interface FindOneRequest {
  id?: string | undefined;
  code?: string | undefined;
}

export interface FindOneResponse {
  order: OrderData | undefined;
}

/** FindMany */
export interface FindManyRequest {
  userId: string;
  status: OrderStatus;
}

export interface FindManyResponse {
  orders: OrderData[];
}

/** UpdateStatus */
export interface UpdateStatusRequest {
  id?: string | undefined;
  code?: string | undefined;
  status: OrderStatus;
}

export interface OrderWorkflowParams {
  orderCode: string;
  userId: string;
  totalAmount: number;
}

export interface OrderWorkflowResult {
  orderCode: string;
  status: string;
  errorMessage: string;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  create(request: CreateRequest): Observable<CreateResponse>;

  findOne(request: FindOneRequest): Observable<FindOneResponse>;

  findMany(request: FindManyRequest): Observable<FindManyResponse>;

  updateStatus(request: UpdateStatusRequest): Observable<Empty>;
}

export interface OrderServiceController {
  create(request: CreateRequest): Promise<CreateResponse> | Observable<CreateResponse> | CreateResponse;

  findOne(request: FindOneRequest): Promise<FindOneResponse> | Observable<FindOneResponse> | FindOneResponse;

  findMany(request: FindManyRequest): Promise<FindManyResponse> | Observable<FindManyResponse> | FindManyResponse;

  updateStatus(request: UpdateStatusRequest): void;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "findOne", "findMany", "updateStatus"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
